#!/usr/bin/env bash
#
# A light wrapper for using the templates building script. This is deliberately
# light, so that users should never have to update this script once they have
# it, but will always have access to the latest templates.
#
# Please see https://github.com/qcr/code_templates for full details on how
# things work, and instructions on how to add your own templates. The more
# templates the merrier!
#
# Author: Ben Talbot
# Version: 0.2.0

bash <(curl -s -L --compressed \
  https://github.com/qcr/code_templates/raw/master/use_template ) "$@"
