#!/usr/bin/env bash
#
# Where the real work is done. This script can be updated more frequently as
# it's shielded behind ./qcr_templates.
#
# This should maybe turn into Python if it grows any more?

set -euo pipefail
IFS=$'\n\t'

################################################################################
############################### Global settings ################################
################################################################################

SETTINGS_FILENAME=".settings.yaml"
TMP_LOCATION="/tmp/qcr_templates"
HACK_LOCATION="/home/ben/repos/code_templates"

TYPES=("basic" "yesno")

################################################################################
############################### Helper functions ###############################
################################################################################

function chunk_count() {
  # $1 chunk size, $2... array values
  sz="$1"; shift
  echo "$(( ($#+$sz-1)/$sz ))"
}

function chunk() {
  # $1 chunk size, $2 chunk number, $3... array values
  sz="$1"; num="$2"; shift $((sz*(num-1) + 2))
  for i in $(seq 1 $sz); do
    echo "${1:-}"
    shift
  done
}

function heading() {
  # $1 heading text
  char="-"
  text=" ${1:-} "
  (( left_pad=(80 - ${#text})/2 ))
  (( right_pad=(81 - ${#text})/2 ))
  printf "\n"; printf "%.0s$char" {1..80}; printf "\n"
  printf "%.0s$char" $(seq 1 $left_pad)
  printf "$text"
  printf "%.0s$char" $(seq 1 $right_pad)
  printf "\n"; printf "%.0s$char" {1..80}; printf "\n"
}

function prompt_value() {
  # $1 text, $2 default value string (can be empty), $3 type (can be empty)
  text="$(echo "${1:-}" | sed 's/^"//; s/"$//')"
  default="${2:-}"
  type="$(echo "${3:-}" | sed 's/^"//; s/"$//')"
  if [ -n "$default" ] && echo "$default" | grep -q '^"'; then
    default="$(echo "$default" | sed 's/"//g')"
  elif [ -n "$default" ]; then
    default="$(eval echo "$default")"
  fi
  default_string="$([ -n "$default" ] && echo "$default" || \
    echo "leave blank to skip")"
  valid=
  while [ -z "$valid" ]; do
    read -p "$text ($default_string): " value
    if [ "$type" == "${TYPES[1]}" ]; then
      if [ -z "$value" ] || echo "${value,,}" | grep -qE '^(y|yes|n|no)'; then
        valid=1
      fi
    else
      valid=1
    fi
  done
  [ -z "$value" ] && echo "$default" || echo "$value"
}


################################################################################
################################# Main script ##################################
################################################################################

# Get a local copy of the templates repo
heading "Getting latest templates"
if [ -d "$TMP_LOCATION" ]; then rm -rf "$TMP_LOCATION"; fi
mkdir -p "$TMP_LOCATION"
git clone --depth 1 -b develop https://github.com/qcr/templates \
  "$TMP_LOCATION"
printf "Done\n"

# Each directory denotes a valid template, process the user's selection
templates=($(find "$HACK_LOCATION" -mindepth 1 -maxdepth 1 -type d \
  -not -name '.git' -exec basename {} \;))
if [ -z "${1:-}" ] || ! printf '%s\n' "${templates[@]}" | \
    grep -q "^$1$"; then
  printf "\nERROR: %s"  \
    "Invalid template provided ('${1:-}'). Please select one of:"
  printf "\n\t%s" "${templates[@]}"
  printf "\n"
  exit 1
fi

# Prompt user for variable values (using hacky YAML parsing)
heading "Prompting user settings"
template="$1"
settings_file="$HACK_LOCATION/$template/$SETTINGS_FILENAME" 
keyvalues=()
if [ -f "$settings_file" ]; then
  key=
  text=
  default=
  type="${TYPES[0]}"
  prompts=()
  while read l; do
    if echo "$l" | grep -q '^[^ ]*:'; then
      if [ -n "$key" ]; then prompts+=("$key" "$text" "$default" "$type"); fi
      key="$(echo "$l" | sed 's/^\([^:]*\).*/\1/')"
      text=
      default=
      type="${TYPES[0]}"
    elif echo "$l" | grep -q '^ *text: '; then
      text="$(echo "$l" | sed 's/^ *text: *\(.*\)$/\1/')"
    elif echo "$l" | grep -q '^ *default: '; then
      default="$(echo "$l" | sed 's/^ *default: *\(.*\)$/\1/')"
    elif echo "$l" | grep -q '^ *type: '; then
      type="$(echo "$l" | sed 's/^ *type: *\(.*\)$/\1/')"
    fi
  done < "$settings_file"
  if [ -n "$key" ]; then prompts+=("$key" "$text" "$default" "$type"); fi

  for i in $(seq 1 $(chunk_count 4 "${prompts[@]}")); do
    c=($(chunk 4 $i "${prompts[@]}"))
    keyvalues+=("${c[0]}" "$(prompt_value "${c[1]}" "${c[2]}" "${c[3]}")")
  done
else
  echo -e "Skipping due to no custom settings found in:\n\t$settings_file"
fi

# Create from template in local directory
heading "Creating project from template"
rsync -av "$HACK_LOCATION/$template/" .
rm -vf "$SETTINGS_FILENAME"

# Modify local directory based on variable settings
heading "Applying user settings to template"

printf "Removing unnecessary directories:\n"

